name=msnatt-switch-plugin
version=1.0.0
author=msnatt
maintainer=msnatt
sentence=Switch plugin for KB-IDE
paragraph=Switch plugin for KB-IDE
category=
url=http://www.kbide.org
architectures=esp32,arduino-esp32
includes=switch.h
